[package]
name = "heretek-drop-shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

description = "Shared types and errors used across all Heretek-Drop sub-crates."

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
url = "2.5"
